#MakeFile

# variaveis
INCLUDES = frequencies.h
SOURCES = main.c frequencies.c
OBJFILES = main.o frequencies.o
EXEC = ex14.out

# Suffix rules
.SUFFIXES : .c .o

.c.o:
	gcc -Wall -g -c $<

${EXEC}: ${OBJFILES}
	gcc -Wall -g -o ${EXEC} ${OBJFILES}

${OBJFILES}: ${SOURCES} ${INCLUDES}

run: ${EXEC}
	./${EXEC}

clean: 
	rm -f *.o ${EXEC}