#MakeFile

# variaveis
INCLUDES = capitalize.h
SOURCES = main.c capitalize.c
OBJFILES = main.o capitalize.o
EXEC = ex12.out

# Suffix rules
.SUFFIXES : .c .o

.c.o:
	gcc -Wall -g -c $<

${EXEC}: ${OBJFILES}
	gcc -Wall -g -o ${EXEC} ${OBJFILES}

${OBJFILES}: ${SOURCES} ${INCLUDES}

run: ${EXEC}
	./${EXEC}

clean: 
	rm -f *.o ${EXEC}